// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvbcJFuK2vRu5TLruRbDv_2re_VxSJBOI',
    appId: '1:900540522216:web:02cb8d6e3e1565132b335d',
    messagingSenderId: '900540522216',
    projectId: 'flutter-firebase-app-21540',
    authDomain: 'flutter-firebase-app-21540.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-21540.firebasestorage.app',
    measurementId: 'G-X1NRY383N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgrK_GKr05_WOwzPvn2vPJp8XlOnhggw',
    appId: '1:900540522216:android:59d42f8fe957abbd2b335d',
    messagingSenderId: '900540522216',
    projectId: 'flutter-firebase-app-21540',
    storageBucket: 'flutter-firebase-app-21540.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj75boZvp9A_hlNWPNrtKEP2ZBc85zaT8',
    appId: '1:900540522216:ios:1e01c5512dc4589b2b335d',
    messagingSenderId: '900540522216',
    projectId: 'flutter-firebase-app-21540',
    storageBucket: 'flutter-firebase-app-21540.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj75boZvp9A_hlNWPNrtKEP2ZBc85zaT8',
    appId: '1:900540522216:ios:1e01c5512dc4589b2b335d',
    messagingSenderId: '900540522216',
    projectId: 'flutter-firebase-app-21540',
    storageBucket: 'flutter-firebase-app-21540.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvbcJFuK2vRu5TLruRbDv_2re_VxSJBOI',
    appId: '1:900540522216:web:f4862f2c047363752b335d',
    messagingSenderId: '900540522216',
    projectId: 'flutter-firebase-app-21540',
    authDomain: 'flutter-firebase-app-21540.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-21540.firebasestorage.app',
    measurementId: 'G-NFJEWW9RV7',
  );
}
